// Generated by unreal-angelscript-forge. Do not edit.
void* ForgeInternalAddress_900D6BC06D4C3EB1()
{
    return reinterpret_cast<void*>(static_cast<float (*)(float)>(&ForgeMvpFixture::InternalBias));
}
