// Generated by unreal-angelscript-forge. Do not edit.
#include "ForgeBindingRegistry.h"
#include "MatterFluxTests.forge.manifest.h"
#include "ForgeMvpFixture.h"
#include <type_traits>

extern void* ForgeInternalAddress_900D6BC06D4C3EB1();

namespace
{

}



namespace
{
template <typename TMemberFunction>
void* ForgeMemberFunctionAddress(TMemberFunction MemberFunction)
{
    static_assert(std::is_member_function_pointer_v<TMemberFunction>,
        "Forge member entry extraction requires a member-function pointer");
    static_assert(
        sizeof(TMemberFunction) == sizeof(void*) ||
        sizeof(TMemberFunction) == sizeof(void*) * 2,
        "Forge supports the verified 8-byte and 16-byte Win64 MSVC member-pointer representations");
    uint8 Representation[sizeof(TMemberFunction)]{};
    FMemory::Memcpy(Representation, &MemberFunction, sizeof(TMemberFunction));
    void* Address = nullptr;
    FMemory::Memcpy(&Address, Representation, sizeof(Address));
    checkf(Address != nullptr, TEXT("Forge member-function entry is null"));
    return Address;
}

template <typename Tag, typename Tag::Type Value>
struct TForgePrivateAccess
{
    friend typename Tag::Type ForgeResolveAccess(Tag)
    {
        return Value;
    }
};

static constexpr FForgeEnumValueBinding EnumValues_FORGEMVPFIXTURE_EIMPACTKIND[] = {
    FForgeEnumValueBinding{ TEXT("Light"), 1 },
    FForgeEnumValueBinding{ TEXT("Heavy"), 4 }
};

static void RegisterType_FORGEMVPFIXTURE_EIMPACTKIND(IForgeBindingRegistry& Registry)
{
    static_assert(sizeof(ForgeMvpFixture::EImpactKind) <= sizeof(int32),
        "Forge enum bindings currently require a 32-bit-or-smaller underlying type");
    Registry.RegisterType(FForgeTypeBinding{
        EForgeValueType::Enum,
        TEXT("EImpactKind"),
        TEXT("ForgeMvpFixture::EImpactKind"),
        FName(TEXT("MatterFluxTests")),
        sizeof(ForgeMvpFixture::EImpactKind),
        TConstArrayView<FForgeTypeFieldBinding>(),
        TConstArrayView<FForgeEnumValueBinding>(EnumValues_FORGEMVPFIXTURE_EIMPACTKIND),
        TConstArrayView<FForgeTypeRef>()
    });
}

static void RegisterType_FORGEMVPFIXTURE_FDAMAGECALCULATOR(IForgeBindingRegistry& Registry)
{
    static_assert(sizeof(ForgeMvpFixture::FDamageCalculator) > 0,
        "Forge native class descriptor requires a complete type");
    static_assert(alignof(ForgeMvpFixture::FDamageCalculator) > 0,
        "Forge native class descriptor requires a valid alignment");
    FForgeTypeBinding Binding{
        EForgeValueType::NativeObject,
        TEXT("ForgeMvpFixture::FDamageCalculator"),
        TEXT("ForgeMvpFixture::FDamageCalculator"),
        FName(TEXT("MatterFluxTests")),
        sizeof(ForgeMvpFixture::FDamageCalculator),
        TConstArrayView<FForgeTypeFieldBinding>(),
        TConstArrayView<FForgeEnumValueBinding>(),
        TConstArrayView<FForgeTypeRef>(),
        TEXT("sha256:5e9fd499d6e5604c1e5c458f91debad0ef02b01f9e5a52c05dfb77f061f875de"),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        alignof(ForgeMvpFixture::FDamageCalculator),
        TConstArrayView<FForgeBaseTypeBinding>(),
        EForgeInstanceCapability::BorrowedRead | EForgeInstanceCapability::BorrowedWrite | EForgeInstanceCapability::MethodCall,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        TEXT(""),
        TEXT(""),
        TEXT("")
    };
    Binding.Constructors = TConstArrayView<FForgeOwnedConstructorBinding>();
    Registry.RegisterType(Binding);
}

static constexpr FForgeTypeFieldBinding Fields_FORGEMVPFIXTURE_FIMPACTDATA[] = {
    FForgeTypeFieldBinding{ TEXT("Amount"), FForgeTypeRef{ EForgeValueType::Float, TEXT("float") }, STRUCT_OFFSET(ForgeMvpFixture::FImpactData, Amount) },
    FForgeTypeFieldBinding{ TEXT("Kind"), FForgeTypeRef{ EForgeValueType::Enum, TEXT("EImpactKind") }, STRUCT_OFFSET(ForgeMvpFixture::FImpactData, Kind) }
};

static void RegisterType_FORGEMVPFIXTURE_FIMPACTDATA(IForgeBindingRegistry& Registry)
{
    static_assert(std::is_trivially_copyable_v<ForgeMvpFixture::FImpactData>,
        "Forge generated struct bindings require trivially-copyable types");
    static_assert(std::is_trivially_default_constructible_v<ForgeMvpFixture::FImpactData>,
        "Forge generated struct bindings require trivially-default-constructible types");
    static_assert(std::is_standard_layout_v<ForgeMvpFixture::FImpactData>,
        "Forge generated struct bindings require standard-layout types");
    FForgeTypeBinding Binding{
        EForgeValueType::Struct,
        TEXT("FImpactData"),
        TEXT("ForgeMvpFixture::FImpactData"),
        FName(TEXT("MatterFluxTests")),
        sizeof(ForgeMvpFixture::FImpactData),
        TConstArrayView<FForgeTypeFieldBinding>(Fields_FORGEMVPFIXTURE_FIMPACTDATA),
        TConstArrayView<FForgeEnumValueBinding>(),
        TConstArrayView<FForgeTypeRef>()
    };
    Registry.RegisterType(Binding);
}

struct FForgeFieldAccessTag_5F1C8567A6942FCA
{
    using Type = float ForgeMvpFixture::FDamageCalculator::*;
    friend Type ForgeResolveAccess(FForgeFieldAccessTag_5F1C8567A6942FCA);
};
template struct TForgePrivateAccess<
    FForgeFieldAccessTag_5F1C8567A6942FCA,
    static_cast<FForgeFieldAccessTag_5F1C8567A6942FCA::Type>(&ForgeMvpFixture::FDamageCalculator::Multiplier)>;
static FForgeInvokeResult GetField_5F1C8567A6942FCA(void* Instance, FForgeValue& OutValue)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field getter requires an instance"));
    }
    const auto Member = ForgeResolveAccess(FForgeFieldAccessTag_5F1C8567A6942FCA{});
    OutValue = FForgeValue::FromFloat(static_cast<const ForgeMvpFixture::FDamageCalculator*>(Instance)->*Member);
    return FForgeInvokeResult::Success();
}

static FForgeInvokeResult SetField_5F1C8567A6942FCA(void* Instance, const FForgeValue& Value)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field setter requires an instance"));
    }
    const auto Member = ForgeResolveAccess(FForgeFieldAccessTag_5F1C8567A6942FCA{});
    static_cast<ForgeMvpFixture::FDamageCalculator*>(Instance)->*Member = Value.AsFloat();
    return FForgeInvokeResult::Success();
}

static void RegisterField_5F1C8567A6942FCA(IForgeBindingRegistry& Registry)
{
    Registry.RegisterField(FForgeFieldBinding{
        TEXT("sha256:5f1c8567a6942fcaac4a4b067bdf432fee8f9b94193963bdf88309fa702f90eb"),
        TEXT("ForgeMvpFixture::FDamageCalculator::Multiplier"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        EForgeAccessSpecifier::Private,
        TEXT("ForgeMvpFixture::FDamageCalculator"),
        TEXT("sha256:5e9fd499d6e5604c1e5c458f91debad0ef02b01f9e5a52c05dfb77f061f875de"),
        false,
        false,
        TEXT("Get_ForgeMvpFixture_FDamageCalculator_Multiplier_5f1c8567"),
        TEXT("Set_ForgeMvpFixture_FDamageCalculator_Multiplier_5f1c8567"),
        &GetField_5F1C8567A6942FCA,
        &SetField_5F1C8567A6942FCA
    });
}



static constexpr FForgeTypeRef ParameterTypes_0EE947E2535CD0B3[] = { FForgeTypeRef{ EForgeValueType::Vector, TEXT("FVector"), FForgeTypeRef::EPassingMode::ConstReference } };
using FNativeFunction_0EE947E2535CD0B3 = FVector (*)(const FVector &);

static FForgeInvokeResult Invoke_0EE947E2535CD0B3(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_0EE947E2535CD0B3>(FunctionAddress);

    OutReturn = FForgeValue::FromVector(NativeFunction(Arguments[0].AsVector()));
    return FForgeInvokeResult::Success();
}

static FVector Replacement_0EE947E2535CD0B3(const FVector & Position)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromVector(Position) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:0ee947e2535cd0b373ad1f3c03c39deea9b2e88f81f2e8690c899fddb6e59008"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsVector();
}

static void Register_0EE947E2535CD0B3(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:0ee947e2535cd0b373ad1f3c03c39deea9b2e88f81f2e8690c899fddb6e59008"),
        TEXT("ForgeMvpFixture::OffsetPosition"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<FVector (*)(const FVector &)>(&ForgeMvpFixture::OffsetPosition)),
        reinterpret_cast<void*>(&Replacement_0EE947E2535CD0B3),
        &Invoke_0EE947E2535CD0B3,
        FForgeTypeRef{ EForgeValueType::Vector, TEXT("FVector") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_0EE947E2535CD0B3),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_186B74744D673BEC[] = { FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_186B74744D673BEC = float (*)(const ForgeMvpFixture::FDamageCalculator*, float);

static FForgeInvokeResult Invoke_186B74744D673BEC(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_186B74744D673BEC>(FunctionAddress);

    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge instance method requires an instance"));
    }
    const auto MemberFunction = static_cast<float (ForgeMvpFixture::FDamageCalculator::*)(float) const>(&ForgeMvpFixture::FDamageCalculator::CallSecret);
    if (FunctionAddress == ForgeMemberFunctionAddress(MemberFunction))
    {
        OutReturn = FForgeValue::FromFloat((static_cast<const ForgeMvpFixture::FDamageCalculator*>(Instance)->*MemberFunction)(Arguments[0].AsFloat()));
    }
    else
    {
        OutReturn = FForgeValue::FromFloat(NativeFunction(static_cast<const ForgeMvpFixture::FDamageCalculator*>(Instance), Arguments[0].AsFloat()));
    }
    return FForgeInvokeResult::Success();
}

static float Replacement_186B74744D673BEC(const ForgeMvpFixture::FDamageCalculator* Self, float Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromFloat(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:186b74744d673bec35f6f23a22929d658d26d87c8a91e32da76ed8de993d2bb1"),
        const_cast<void*>(static_cast<const void*>(Self)),
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_186B74744D673BEC(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:186b74744d673bec35f6f23a22929d658d26d87c8a91e32da76ed8de993d2bb1"),
        TEXT("ForgeMvpFixture::FDamageCalculator::CallSecret"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        ForgeMemberFunctionAddress(static_cast<float (ForgeMvpFixture::FDamageCalculator::*)(float) const>(&ForgeMvpFixture::FDamageCalculator::CallSecret)),
        reinterpret_cast<void*>(&Replacement_186B74744D673BEC),
        &Invoke_186B74744D673BEC,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_186B74744D673BEC),
        true,
        TEXT("ForgeMvpFixture::FDamageCalculator"),
        true,
        true,
        TEXT("sha256:5e9fd499d6e5604c1e5c458f91debad0ef02b01f9e5a52c05dfb77f061f875de"),
        TEXT("ForgeMvpFixture_FDamageCalculator_CallSecret_186b7474"),
        true
    });
}

static constexpr FForgeTypeRef ParameterTypes_18B286874F26CA78[] = { FForgeTypeRef{ EForgeValueType::Object, TEXT("UObjectHandle") }, FForgeTypeRef{ EForgeValueType::Name, TEXT("FName"), FForgeTypeRef::EPassingMode::ConstReference }, FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_18B286874F26CA78 = float (*)(UObject *, const FName &, float);

static FForgeInvokeResult Invoke_18B286874F26CA78(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 3)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(3, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_18B286874F26CA78>(FunctionAddress);

    OutReturn = FForgeValue::FromFloat(NativeFunction(Cast<UObject>(Arguments[0].AsObject()), Arguments[1].AsName(), Arguments[2].AsFloat()));
    return FForgeInvokeResult::Success();
}

static float Replacement_18B286874F26CA78(UObject * Object, const FName & FunctionName, float Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromObject(Object), FForgeValue::FromName(FunctionName), FForgeValue::FromFloat(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:18b286874f26ca78865dee8cc39c2f24b183e4cda6a4626bdebb5eb0c91a9e54"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_18B286874F26CA78(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:18b286874f26ca78865dee8cc39c2f24b183e4cda6a4626bdebb5eb0c91a9e54"),
        TEXT("ForgeMvpFixture::InvokeReflectedFloat"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<float (*)(UObject *, const FName &, float)>(&ForgeMvpFixture::InvokeReflectedFloat)),
        reinterpret_cast<void*>(&Replacement_18B286874F26CA78),
        &Invoke_18B286874F26CA78,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_18B286874F26CA78),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

struct FForgeAccessTag_3D7C51D2492F7F0D
{
    using Type = float (ForgeMvpFixture::FDamageCalculator::*)(float) const;
    friend Type ForgeResolveAccess(FForgeAccessTag_3D7C51D2492F7F0D);
};
template struct TForgePrivateAccess<
    FForgeAccessTag_3D7C51D2492F7F0D,
    static_cast<FForgeAccessTag_3D7C51D2492F7F0D::Type>(&ForgeMvpFixture::FDamageCalculator::SecretScale)>;
static constexpr FForgeTypeRef ParameterTypes_3D7C51D2492F7F0D[] = { FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_3D7C51D2492F7F0D = float (*)(const ForgeMvpFixture::FDamageCalculator*, float);

static FForgeInvokeResult Invoke_3D7C51D2492F7F0D(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_3D7C51D2492F7F0D>(FunctionAddress);

    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge instance method requires an instance"));
    }
    const auto MemberFunction = ForgeResolveAccess(FForgeAccessTag_3D7C51D2492F7F0D{});
    if (FunctionAddress == ForgeMemberFunctionAddress(MemberFunction))
    {
        OutReturn = FForgeValue::FromFloat((static_cast<const ForgeMvpFixture::FDamageCalculator*>(Instance)->*MemberFunction)(Arguments[0].AsFloat()));
    }
    else
    {
        OutReturn = FForgeValue::FromFloat(NativeFunction(static_cast<const ForgeMvpFixture::FDamageCalculator*>(Instance), Arguments[0].AsFloat()));
    }
    return FForgeInvokeResult::Success();
}

static float Replacement_3D7C51D2492F7F0D(const ForgeMvpFixture::FDamageCalculator* Self, float Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromFloat(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:3d7c51d2492f7f0dc59420b23f56a94157bd19e8bb67b95c8ed2db03f321380b"),
        const_cast<void*>(static_cast<const void*>(Self)),
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_3D7C51D2492F7F0D(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:3d7c51d2492f7f0dc59420b23f56a94157bd19e8bb67b95c8ed2db03f321380b"),
        TEXT("ForgeMvpFixture::FDamageCalculator::SecretScale"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        ForgeMemberFunctionAddress(ForgeResolveAccess(FForgeAccessTag_3D7C51D2492F7F0D{})),
        reinterpret_cast<void*>(&Replacement_3D7C51D2492F7F0D),
        &Invoke_3D7C51D2492F7F0D,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_3D7C51D2492F7F0D),
        true,
        TEXT("ForgeMvpFixture::FDamageCalculator"),
        true,
        true,
        TEXT("sha256:5e9fd499d6e5604c1e5c458f91debad0ef02b01f9e5a52c05dfb77f061f875de"),
        TEXT("ForgeMvpFixture_FDamageCalculator_SecretScale_3d7c51d2"),
        true
    });
}

static constexpr FForgeTypeRef ParameterTypes_4D2141DCFE25CE23[] = { FForgeTypeRef{ EForgeValueType::String, TEXT("FString"), FForgeTypeRef::EPassingMode::ConstReference }, FForgeTypeRef{ EForgeValueType::Name, TEXT("FName"), FForgeTypeRef::EPassingMode::ConstReference }, FForgeTypeRef{ EForgeValueType::Vector, TEXT("FVector"), FForgeTypeRef::EPassingMode::ConstReference } };
using FNativeFunction_4D2141DCFE25CE23 = FString (*)(const FString &, const FName &, const FVector &);

static FForgeInvokeResult Invoke_4D2141DCFE25CE23(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 3)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(3, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_4D2141DCFE25CE23>(FunctionAddress);

    OutReturn = FForgeValue::FromString(NativeFunction(Arguments[0].AsString(), Arguments[1].AsName(), Arguments[2].AsVector()));
    return FForgeInvokeResult::Success();
}

static FString Replacement_4D2141DCFE25CE23(const FString & Label, const FName & Category, const FVector & Position)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromString(Label), FForgeValue::FromName(Category), FForgeValue::FromVector(Position) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:4d2141dcfe25ce233cf5612aea39e680d07c54b3e08351595b7aa6a16a756e63"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsString();
}

static void Register_4D2141DCFE25CE23(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:4d2141dcfe25ce233cf5612aea39e680d07c54b3e08351595b7aa6a16a756e63"),
        TEXT("ForgeMvpFixture::DescribeImpact"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<FString (*)(const FString &, const FName &, const FVector &)>(&ForgeMvpFixture::DescribeImpact)),
        reinterpret_cast<void*>(&Replacement_4D2141DCFE25CE23),
        &Invoke_4D2141DCFE25CE23,
        FForgeTypeRef{ EForgeValueType::String, TEXT("FString") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_4D2141DCFE25CE23),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_900D6BC06D4C3EB1[] = { FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_900D6BC06D4C3EB1 = float (*)(float);

static FForgeInvokeResult Invoke_900D6BC06D4C3EB1(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_900D6BC06D4C3EB1>(FunctionAddress);

    OutReturn = FForgeValue::FromFloat(NativeFunction(Arguments[0].AsFloat()));
    return FForgeInvokeResult::Success();
}

static float Replacement_900D6BC06D4C3EB1(float Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromFloat(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:900d6bc06d4c3eb1850a666b801ac34687d7bbd7cec852903a5a39ef78ddb581"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_900D6BC06D4C3EB1(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:900d6bc06d4c3eb1850a666b801ac34687d7bbd7cec852903a5a39ef78ddb581"),
        TEXT("ForgeMvpFixture::InternalBias"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        ::ForgeInternalAddress_900D6BC06D4C3EB1(),
        reinterpret_cast<void*>(&Replacement_900D6BC06D4C3EB1),
        &Invoke_900D6BC06D4C3EB1,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_900D6BC06D4C3EB1),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_99EB31EBBB910D86[] = { FForgeTypeRef{ EForgeValueType::Float, TEXT("float") }, FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_99EB31EBBB910D86 = float (*)(float, float);

static FForgeInvokeResult Invoke_99EB31EBBB910D86(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 2)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(2, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_99EB31EBBB910D86>(FunctionAddress);

    OutReturn = FForgeValue::FromFloat(NativeFunction(Arguments[0].AsFloat(), Arguments[1].AsFloat()));
    return FForgeInvokeResult::Success();
}

static float Replacement_99EB31EBBB910D86(float BaseDamage, float Distance)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromFloat(BaseDamage), FForgeValue::FromFloat(Distance) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:99eb31ebbb910d8643029ddfbb8721c5ead4b460a01f85938ac9ee7a24b0f7be"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_99EB31EBBB910D86(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:99eb31ebbb910d8643029ddfbb8721c5ead4b460a01f85938ac9ee7a24b0f7be"),
        TEXT("ForgeMvpFixture::CalculateDamage"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<float (*)(float, float)>(&ForgeMvpFixture::CalculateDamage)),
        reinterpret_cast<void*>(&Replacement_99EB31EBBB910D86),
        &Invoke_99EB31EBBB910D86,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_99EB31EBBB910D86),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_C3086EFBE4AA3306[] = { FForgeTypeRef{ EForgeValueType::Struct, TEXT("FImpactData"), FForgeTypeRef::EPassingMode::ConstReference } };
using FNativeFunction_C3086EFBE4AA3306 = ForgeMvpFixture::FImpactData (*)(const ForgeMvpFixture::FImpactData &);

static FForgeInvokeResult Invoke_C3086EFBE4AA3306(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_C3086EFBE4AA3306>(FunctionAddress);

    OutReturn = FForgeValue::FromStruct(NativeFunction(Arguments[0].AsStruct<ForgeMvpFixture::FImpactData>(TEXT("FImpactData"))), TEXT("FImpactData"));
    return FForgeInvokeResult::Success();
}

static ForgeMvpFixture::FImpactData Replacement_C3086EFBE4AA3306(const ForgeMvpFixture::FImpactData & Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromStruct(Value, TEXT("FImpactData")) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:c3086efbe4aa3306eebd8fcaa57e71c04fc8182016e3eccc78bef5c84c77dff6"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsStruct<ForgeMvpFixture::FImpactData>(TEXT("FImpactData"));
}

static void Register_C3086EFBE4AA3306(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:c3086efbe4aa3306eebd8fcaa57e71c04fc8182016e3eccc78bef5c84c77dff6"),
        TEXT("ForgeMvpFixture::BoostImpact"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<ForgeMvpFixture::FImpactData (*)(const ForgeMvpFixture::FImpactData &)>(&ForgeMvpFixture::BoostImpact)),
        reinterpret_cast<void*>(&Replacement_C3086EFBE4AA3306),
        &Invoke_C3086EFBE4AA3306,
        FForgeTypeRef{ EForgeValueType::Struct, TEXT("FImpactData") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_C3086EFBE4AA3306),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_CAC09EC538D360B3[] = { FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_CAC09EC538D360B3 = float (*)(float);

static FForgeInvokeResult Invoke_CAC09EC538D360B3(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_CAC09EC538D360B3>(FunctionAddress);

    OutReturn = FForgeValue::FromFloat(NativeFunction(Arguments[0].AsFloat()));
    return FForgeInvokeResult::Success();
}

static float Replacement_CAC09EC538D360B3(float Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromFloat(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:cac09ec538d360b34aef5ab80fa272c651f448ef2d1f13a540c609acd0adde56"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_CAC09EC538D360B3(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:cac09ec538d360b34aef5ab80fa272c651f448ef2d1f13a540c609acd0adde56"),
        TEXT("ForgeMvpFixture::CallInternalBias"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<float (*)(float)>(&ForgeMvpFixture::CallInternalBias)),
        reinterpret_cast<void*>(&Replacement_CAC09EC538D360B3),
        &Invoke_CAC09EC538D360B3,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_CAC09EC538D360B3),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_DE31F1E71A339BE7[] = { FForgeTypeRef{ EForgeValueType::Enum, TEXT("EImpactKind") } };
using FNativeFunction_DE31F1E71A339BE7 = ForgeMvpFixture::EImpactKind (*)(ForgeMvpFixture::EImpactKind);

static FForgeInvokeResult Invoke_DE31F1E71A339BE7(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_DE31F1E71A339BE7>(FunctionAddress);

    OutReturn = FForgeValue::FromEnum(static_cast<int32>(NativeFunction(static_cast<ForgeMvpFixture::EImpactKind>(Arguments[0].AsEnum(TEXT("EImpactKind"))))), TEXT("EImpactKind"));
    return FForgeInvokeResult::Success();
}

static ForgeMvpFixture::EImpactKind Replacement_DE31F1E71A339BE7(ForgeMvpFixture::EImpactKind Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromEnum(static_cast<int32>(Value), TEXT("EImpactKind")) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:de31f1e71a339be7b230d80b6f2e312a68bbbb472e99c2268cfddafd17a93488"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return static_cast<ForgeMvpFixture::EImpactKind>(ReturnValue.AsEnum(TEXT("EImpactKind")));
}

static void Register_DE31F1E71A339BE7(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:de31f1e71a339be7b230d80b6f2e312a68bbbb472e99c2268cfddafd17a93488"),
        TEXT("ForgeMvpFixture::OppositeImpact"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<ForgeMvpFixture::EImpactKind (*)(ForgeMvpFixture::EImpactKind)>(&ForgeMvpFixture::OppositeImpact)),
        reinterpret_cast<void*>(&Replacement_DE31F1E71A339BE7),
        &Invoke_DE31F1E71A339BE7,
        FForgeTypeRef{ EForgeValueType::Enum, TEXT("EImpactKind") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_DE31F1E71A339BE7),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_FA641992B9223CA0[] = { FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_FA641992B9223CA0 = float (*)(const ForgeMvpFixture::FDamageCalculator*, float);

static FForgeInvokeResult Invoke_FA641992B9223CA0(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_FA641992B9223CA0>(FunctionAddress);

    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge instance method requires an instance"));
    }
    const auto MemberFunction = static_cast<float (ForgeMvpFixture::FDamageCalculator::*)(float) const>(&ForgeMvpFixture::FDamageCalculator::Scale);
    if (FunctionAddress == ForgeMemberFunctionAddress(MemberFunction))
    {
        OutReturn = FForgeValue::FromFloat((static_cast<const ForgeMvpFixture::FDamageCalculator*>(Instance)->*MemberFunction)(Arguments[0].AsFloat()));
    }
    else
    {
        OutReturn = FForgeValue::FromFloat(NativeFunction(static_cast<const ForgeMvpFixture::FDamageCalculator*>(Instance), Arguments[0].AsFloat()));
    }
    return FForgeInvokeResult::Success();
}

static float Replacement_FA641992B9223CA0(const ForgeMvpFixture::FDamageCalculator* Self, float Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromFloat(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:fa641992b9223ca0d7bf61714018168c0ae7aaf76e57ad2928040950c0e74be4"),
        const_cast<void*>(static_cast<const void*>(Self)),
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_FA641992B9223CA0(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:fa641992b9223ca0d7bf61714018168c0ae7aaf76e57ad2928040950c0e74be4"),
        TEXT("ForgeMvpFixture::FDamageCalculator::Scale"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        ForgeMemberFunctionAddress(static_cast<float (ForgeMvpFixture::FDamageCalculator::*)(float) const>(&ForgeMvpFixture::FDamageCalculator::Scale)),
        reinterpret_cast<void*>(&Replacement_FA641992B9223CA0),
        &Invoke_FA641992B9223CA0,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_FA641992B9223CA0),
        true,
        TEXT("ForgeMvpFixture::FDamageCalculator"),
        true,
        true,
        TEXT("sha256:5e9fd499d6e5604c1e5c458f91debad0ef02b01f9e5a52c05dfb77f061f875de"),
        TEXT("ForgeMvpFixture_FDamageCalculator_Scale_fa641992"),
        true
    });
}

static constexpr FForgeTypeRef ParameterTypes_FFC993EE2D71F368[] = { FForgeTypeRef{ EForgeValueType::Double, TEXT("double") } };
using FNativeFunction_FFC993EE2D71F368 = int (*)(double);

static FForgeInvokeResult Invoke_FFC993EE2D71F368(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_FFC993EE2D71F368>(FunctionAddress);

    OutReturn = FForgeValue::FromInt32(NativeFunction(Arguments[0].AsDouble()));
    return FForgeInvokeResult::Success();
}

static int Replacement_FFC993EE2D71F368(double Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromDouble(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:ffc993ee2d71f368f8063652fd0d4f56931256646505a542efaa520c4ddd8231"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsInt32();
}

static void Register_FFC993EE2D71F368(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:ffc993ee2d71f368f8063652fd0d4f56931256646505a542efaa520c4ddd8231"),
        TEXT("ForgeMvpFixture::FDamageCalculator::ClampToInt"),
        FName(TEXT("MatterFluxTests")),
        MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<int (*)(double)>(&ForgeMvpFixture::FDamageCalculator::ClampToInt)),
        reinterpret_cast<void*>(&Replacement_FFC993EE2D71F368),
        &Invoke_FFC993EE2D71F368,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_FFC993EE2D71F368),
        false,
        TEXT("ForgeMvpFixture::FDamageCalculator"),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static void RegisterAllBindings(IForgeBindingRegistry& Registry)
{

    RegisterType_FORGEMVPFIXTURE_EIMPACTKIND(Registry);
    RegisterType_FORGEMVPFIXTURE_FDAMAGECALCULATOR(Registry);
    RegisterType_FORGEMVPFIXTURE_FIMPACTDATA(Registry);
    RegisterField_5F1C8567A6942FCA(Registry);

    Register_0EE947E2535CD0B3(Registry);
    Register_186B74744D673BEC(Registry);
    Register_18B286874F26CA78(Registry);
    Register_3D7C51D2492F7F0D(Registry);
    Register_4D2141DCFE25CE23(Registry);
    Register_900D6BC06D4C3EB1(Registry);
    Register_99EB31EBBB910D86(Registry);
    Register_C3086EFBE4AA3306(Registry);
    Register_CAC09EC538D360B3(Registry);
    Register_DE31F1E71A339BE7(Registry);
    Register_FA641992B9223CA0(Registry);
    Register_FFC993EE2D71F368(Registry);
}

static FForgeAutoModuleRegistrar GForgeRegistrar(FForgeModuleBindings{
    FName(TEXT("MatterFluxTests")),
    MATTERFLUXTESTS_FORGE_BUILD_FINGERPRINT,
    &RegisterAllBindings
});
} // namespace
