// Generated by unreal-angelscript-forge. Do not edit.
#include "ForgeBindingRegistry.h"
#include "MatterFlux.forge.manifest.h"
#include "ForgeAuxFixture.h"
#include "Fragment/Fragment2DAsset.h"
#include <type_traits>



namespace
{
static FForgeValue ForgeValueFromNative_TARRAY_INT32(const TArray<int32>& Value);
static TArray<int32> ForgeNativeFromValue_TARRAY_INT32(const FForgeValue& Value);
}



namespace
{
template <typename TMemberFunction>
void* ForgeMemberFunctionAddress(TMemberFunction MemberFunction)
{
    static_assert(std::is_member_function_pointer_v<TMemberFunction>,
        "Forge member entry extraction requires a member-function pointer");
    static_assert(
        sizeof(TMemberFunction) == sizeof(void*) ||
        sizeof(TMemberFunction) == sizeof(void*) * 2,
        "Forge supports the verified 8-byte and 16-byte Win64 MSVC member-pointer representations");
    uint8 Representation[sizeof(TMemberFunction)]{};
    FMemory::Memcpy(Representation, &MemberFunction, sizeof(TMemberFunction));
    void* Address = nullptr;
    FMemory::Memcpy(&Address, Representation, sizeof(Address));
    checkf(Address != nullptr, TEXT("Forge member-function entry is null"));
    return Address;
}

template <typename Tag, typename Tag::Type Value>
struct TForgePrivateAccess
{
    friend typename Tag::Type ForgeResolveAccess(Tag)
    {
        return Value;
    }
};

static void RegisterType_FORGEAUXFIXTURE_TPROJECTACCUMULATOR_INT_7(IForgeBindingRegistry& Registry)
{
    static_assert(sizeof(ForgeAuxFixture::TProjectAccumulator<int, 7>) > 0,
        "Forge native class descriptor requires a complete type");
    static_assert(alignof(ForgeAuxFixture::TProjectAccumulator<int, 7>) > 0,
        "Forge native class descriptor requires a valid alignment");
    FForgeTypeBinding Binding{
        EForgeValueType::NativeObject,
        TEXT("ForgeAuxFixture::TProjectAccumulator<int, 7>"),
        TEXT("ForgeAuxFixture::TProjectAccumulator<int, 7>"),
        FName(TEXT("MatterFlux")),
        sizeof(ForgeAuxFixture::TProjectAccumulator<int, 7>),
        TConstArrayView<FForgeTypeFieldBinding>(),
        TConstArrayView<FForgeEnumValueBinding>(),
        TConstArrayView<FForgeTypeRef>(),
        TEXT("sha256:54fa13f8f3e8f9c9c041e475fd149aad5a5a9fda5206ac5d37d4a570f2d9303e"),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        alignof(ForgeAuxFixture::TProjectAccumulator<int, 7>),
        TConstArrayView<FForgeBaseTypeBinding>(),
        EForgeInstanceCapability::BorrowedRead | EForgeInstanceCapability::BorrowedWrite | EForgeInstanceCapability::MethodCall,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        TEXT(""),
        TEXT(""),
        TEXT("")
    };
    Binding.Constructors = TConstArrayView<FForgeOwnedConstructorBinding>();
    Registry.RegisterType(Binding);
}

static constexpr FForgeTypeRef TemplateArguments_TARRAY_INT32[] = {
    FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") }
};

static FForgeValue ForgeValueFromNative_TARRAY_INT32(const TArray<int32>& Value)
{
    TArray<FForgeValue> Values;
    Values.Reserve(Value.Num());
    for (const int32& Item : Value)
    {
        Values.Add(FForgeValue::FromInt32(Item));
    }
    return FForgeValue::FromContainer(
        EForgeValueType::Array, TEXT("TArray_int"), MoveTemp(Values));
}

static TArray<int32> ForgeNativeFromValue_TARRAY_INT32(const FForgeValue& Value)
{
    const FForgeContainer& Container = Value.AsContainer(
        EForgeValueType::Array, TEXT("TArray_int"));
    TArray<int32> Result;
    Result.Reserve(Container.Values.Num());
    for (const FForgeValue& Item : Container.Values)
    {
        Result.Add(Item.AsInt32());
    }
    return Result;
}

static void RegisterType_TARRAY_INT32(IForgeBindingRegistry& Registry)
{
    Registry.RegisterType(FForgeTypeBinding{
        EForgeValueType::Array,
        TEXT("TArray_int"),
        TEXT("TArray<int32>"),
        FName(TEXT("MatterFlux")),
        sizeof(FForgeContainer),
        TConstArrayView<FForgeTypeFieldBinding>(),
        TConstArrayView<FForgeEnumValueBinding>(),
        TConstArrayView<FForgeTypeRef>(TemplateArguments_TARRAY_INT32)
    });
}

static constexpr FForgeBaseTypeBinding BaseTypes_UFRAGMENT2DASSET[] = {
    FForgeBaseTypeBinding{ TEXT(""), TEXT("UDataAsset"), EForgeAccessSpecifier::Public, false, nullptr }
};

static void RegisterType_UFRAGMENT2DASSET(IForgeBindingRegistry& Registry)
{
    static_assert(sizeof(UFragment2DAsset) > 0,
        "Forge native class descriptor requires a complete type");
    static_assert(alignof(UFragment2DAsset) > 0,
        "Forge native class descriptor requires a valid alignment");
    FForgeTypeBinding Binding{
        EForgeValueType::NativeObject,
        TEXT("UFragment2DAsset"),
        TEXT("UFragment2DAsset"),
        FName(TEXT("MatterFlux")),
        sizeof(UFragment2DAsset),
        TConstArrayView<FForgeTypeFieldBinding>(),
        TConstArrayView<FForgeEnumValueBinding>(),
        TConstArrayView<FForgeTypeRef>(),
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        alignof(UFragment2DAsset),
        TConstArrayView<FForgeBaseTypeBinding>(BaseTypes_UFRAGMENT2DASSET),
        EForgeInstanceCapability::BorrowedRead | EForgeInstanceCapability::BorrowedWrite | EForgeInstanceCapability::MethodCall,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        TEXT(""),
        TEXT(""),
        TEXT("")
    };
    Binding.Constructors = TConstArrayView<FForgeOwnedConstructorBinding>();
    Registry.RegisterType(Binding);
}

static FForgeInvokeResult GetField_5BA73D88F84437D8(void* Instance, FForgeValue& OutValue)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field getter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MinFragmentAreaPixels);
    OutValue = FForgeValue::FromInt32(static_cast<const UFragment2DAsset*>(Instance)->*Member);
    return FForgeInvokeResult::Success();
}

static FForgeInvokeResult SetField_5BA73D88F84437D8(void* Instance, const FForgeValue& Value)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field setter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MinFragmentAreaPixels);
    static_cast<UFragment2DAsset*>(Instance)->*Member = Value.AsInt32();
    return FForgeInvokeResult::Success();
}

static void RegisterField_5BA73D88F84437D8(IForgeBindingRegistry& Registry)
{
    Registry.RegisterField(FForgeFieldBinding{
        TEXT("sha256:5ba73d88f84437d846982a251ea837f3c0372719bae78154676811ffd26f351c"),
        TEXT("UFragment2DAsset::MinFragmentAreaPixels"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") },
        EForgeAccessSpecifier::Public,
        TEXT("UFragment2DAsset"),
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        false,
        false,
        TEXT("Get_UFragment2DAsset_MinFragmentAreaPixels_5ba73d88"),
        TEXT("Set_UFragment2DAsset_MinFragmentAreaPixels_5ba73d88"),
        &GetField_5BA73D88F84437D8,
        &SetField_5BA73D88F84437D8
    });
}

static FForgeInvokeResult GetField_9AB97F2CDA891E45(void* Instance, FForgeValue& OutValue)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field getter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MaskWidth);
    OutValue = FForgeValue::FromInt32(static_cast<const UFragment2DAsset*>(Instance)->*Member);
    return FForgeInvokeResult::Success();
}

static FForgeInvokeResult SetField_9AB97F2CDA891E45(void* Instance, const FForgeValue& Value)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field setter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MaskWidth);
    static_cast<UFragment2DAsset*>(Instance)->*Member = Value.AsInt32();
    return FForgeInvokeResult::Success();
}

static void RegisterField_9AB97F2CDA891E45(IForgeBindingRegistry& Registry)
{
    Registry.RegisterField(FForgeFieldBinding{
        TEXT("sha256:9ab97f2cda891e456db67954c4dfca4603e270717d493d0d0c10c3e953da8328"),
        TEXT("UFragment2DAsset::MaskWidth"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") },
        EForgeAccessSpecifier::Public,
        TEXT("UFragment2DAsset"),
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        false,
        false,
        TEXT("Get_UFragment2DAsset_MaskWidth_9ab97f2c"),
        TEXT("Set_UFragment2DAsset_MaskWidth_9ab97f2c"),
        &GetField_9AB97F2CDA891E45,
        &SetField_9AB97F2CDA891E45
    });
}

static FForgeInvokeResult GetField_B060A83351782ABC(void* Instance, FForgeValue& OutValue)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field getter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MaxFragmentsPerBreak);
    OutValue = FForgeValue::FromInt32(static_cast<const UFragment2DAsset*>(Instance)->*Member);
    return FForgeInvokeResult::Success();
}

static FForgeInvokeResult SetField_B060A83351782ABC(void* Instance, const FForgeValue& Value)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field setter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MaxFragmentsPerBreak);
    static_cast<UFragment2DAsset*>(Instance)->*Member = Value.AsInt32();
    return FForgeInvokeResult::Success();
}

static void RegisterField_B060A83351782ABC(IForgeBindingRegistry& Registry)
{
    Registry.RegisterField(FForgeFieldBinding{
        TEXT("sha256:b060a83351782abcff23cfd642c3d4df15113a6bfdc48243927e5b47185ba48a"),
        TEXT("UFragment2DAsset::MaxFragmentsPerBreak"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") },
        EForgeAccessSpecifier::Public,
        TEXT("UFragment2DAsset"),
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        false,
        false,
        TEXT("Get_UFragment2DAsset_MaxFragmentsPerBreak_b060a833"),
        TEXT("Set_UFragment2DAsset_MaxFragmentsPerBreak_b060a833"),
        &GetField_B060A83351782ABC,
        &SetField_B060A83351782ABC
    });
}

struct FForgeFieldAccessTag_D12954423ABE9235
{
    using Type = int ForgeAuxFixture::TProjectAccumulator<int, 7>::*;
    friend Type ForgeResolveAccess(FForgeFieldAccessTag_D12954423ABE9235);
};
template struct TForgePrivateAccess<
    FForgeFieldAccessTag_D12954423ABE9235,
    static_cast<FForgeFieldAccessTag_D12954423ABE9235::Type>(&ForgeAuxFixture::TProjectAccumulator<int, 7>::Base)>;
static FForgeInvokeResult GetField_D12954423ABE9235(void* Instance, FForgeValue& OutValue)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field getter requires an instance"));
    }
    const auto Member = ForgeResolveAccess(FForgeFieldAccessTag_D12954423ABE9235{});
    OutValue = FForgeValue::FromInt32(static_cast<const ForgeAuxFixture::TProjectAccumulator<int, 7>*>(Instance)->*Member);
    return FForgeInvokeResult::Success();
}

static FForgeInvokeResult SetField_D12954423ABE9235(void* Instance, const FForgeValue& Value)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field setter requires an instance"));
    }
    const auto Member = ForgeResolveAccess(FForgeFieldAccessTag_D12954423ABE9235{});
    static_cast<ForgeAuxFixture::TProjectAccumulator<int, 7>*>(Instance)->*Member = Value.AsInt32();
    return FForgeInvokeResult::Success();
}

static void RegisterField_D12954423ABE9235(IForgeBindingRegistry& Registry)
{
    Registry.RegisterField(FForgeFieldBinding{
        TEXT("sha256:d12954423abe92355f2ba9bce483006d58ec92ad4421442bb680187e60ede7da"),
        TEXT("ForgeAuxFixture::TProjectAccumulator<int, 7>::Base"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int") },
        EForgeAccessSpecifier::Private,
        TEXT("ForgeAuxFixture::TProjectAccumulator<int, 7>"),
        TEXT("sha256:54fa13f8f3e8f9c9c041e475fd149aad5a5a9fda5206ac5d37d4a570f2d9303e"),
        false,
        false,
        TEXT("Get_ForgeAuxFixture_TProjectAccumulator_int_7_Base_d1295442"),
        TEXT("Set_ForgeAuxFixture_TProjectAccumulator_int_7_Base_d1295442"),
        &GetField_D12954423ABE9235,
        &SetField_D12954423ABE9235
    });
}

static FForgeInvokeResult GetField_E5AB6B08EEE4C465(void* Instance, FForgeValue& OutValue)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field getter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MaskHeight);
    OutValue = FForgeValue::FromInt32(static_cast<const UFragment2DAsset*>(Instance)->*Member);
    return FForgeInvokeResult::Success();
}

static FForgeInvokeResult SetField_E5AB6B08EEE4C465(void* Instance, const FForgeValue& Value)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field setter requires an instance"));
    }
    const auto Member = static_cast<int32 UFragment2DAsset::*>(&UFragment2DAsset::MaskHeight);
    static_cast<UFragment2DAsset*>(Instance)->*Member = Value.AsInt32();
    return FForgeInvokeResult::Success();
}

static void RegisterField_E5AB6B08EEE4C465(IForgeBindingRegistry& Registry)
{
    Registry.RegisterField(FForgeFieldBinding{
        TEXT("sha256:e5ab6b08eee4c465173482a07331d31fcd26061c86cd3d75ae3e0952d63136a8"),
        TEXT("UFragment2DAsset::MaskHeight"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") },
        EForgeAccessSpecifier::Public,
        TEXT("UFragment2DAsset"),
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        false,
        false,
        TEXT("Get_UFragment2DAsset_MaskHeight_e5ab6b08"),
        TEXT("Set_UFragment2DAsset_MaskHeight_e5ab6b08"),
        &GetField_E5AB6B08EEE4C465,
        &SetField_E5AB6B08EEE4C465
    });
}

static FForgeInvokeResult GetField_E8E5DAD8B3EEA0FD(void* Instance, FForgeValue& OutValue)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field getter requires an instance"));
    }
    const auto Member = static_cast<float UFragment2DAsset::*>(&UFragment2DAsset::CellSize);
    OutValue = FForgeValue::FromFloat(static_cast<const UFragment2DAsset*>(Instance)->*Member);
    return FForgeInvokeResult::Success();
}

static FForgeInvokeResult SetField_E8E5DAD8B3EEA0FD(void* Instance, const FForgeValue& Value)
{
    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge field setter requires an instance"));
    }
    const auto Member = static_cast<float UFragment2DAsset::*>(&UFragment2DAsset::CellSize);
    static_cast<UFragment2DAsset*>(Instance)->*Member = Value.AsFloat();
    return FForgeInvokeResult::Success();
}

static void RegisterField_E8E5DAD8B3EEA0FD(IForgeBindingRegistry& Registry)
{
    Registry.RegisterField(FForgeFieldBinding{
        TEXT("sha256:e8e5dad8b3eea0fd93288a9eb7d6a7c5248a8f7d7146bdffb890ffd2fa81709c"),
        TEXT("UFragment2DAsset::CellSize"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        EForgeAccessSpecifier::Public,
        TEXT("UFragment2DAsset"),
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        false,
        false,
        TEXT("Get_UFragment2DAsset_CellSize_e8e5dad8"),
        TEXT("Set_UFragment2DAsset_CellSize_e8e5dad8"),
        &GetField_E8E5DAD8B3EEA0FD,
        &SetField_E8E5DAD8B3EEA0FD
    });
}



static constexpr FForgeTypeRef ParameterTypes_168BB1C2275CBE71[] = { FForgeTypeRef{ EForgeValueType::Int32, TEXT("int") } };
using FNativeFunction_168BB1C2275CBE71 = int (*)(const ForgeAuxFixture::TProjectAccumulator<int, 7>*, int);

static FForgeInvokeResult Invoke_168BB1C2275CBE71(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_168BB1C2275CBE71>(FunctionAddress);

    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge instance method requires an instance"));
    }
    const auto MemberFunction = static_cast<int (ForgeAuxFixture::TProjectAccumulator<int, 7>::*)(int) const>(&ForgeAuxFixture::TProjectAccumulator<int, 7>::Add);
    if (FunctionAddress == ForgeMemberFunctionAddress(MemberFunction))
    {
        OutReturn = FForgeValue::FromInt32((static_cast<const ForgeAuxFixture::TProjectAccumulator<int, 7>*>(Instance)->*MemberFunction)(Arguments[0].AsInt32()));
    }
    else
    {
        OutReturn = FForgeValue::FromInt32(NativeFunction(static_cast<const ForgeAuxFixture::TProjectAccumulator<int, 7>*>(Instance), Arguments[0].AsInt32()));
    }
    return FForgeInvokeResult::Success();
}

static int Replacement_168BB1C2275CBE71(const ForgeAuxFixture::TProjectAccumulator<int, 7>* Self, int Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromInt32(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:168bb1c2275cbe71b57570a7dc54c4a8cc6f234f156a0d1750b3a72fd92512e3"),
        const_cast<void*>(static_cast<const void*>(Self)),
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsInt32();
}

static void Register_168BB1C2275CBE71(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:168bb1c2275cbe71b57570a7dc54c4a8cc6f234f156a0d1750b3a72fd92512e3"),
        TEXT("ForgeAuxFixture::TProjectAccumulator<int, 7>::Add"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        ForgeMemberFunctionAddress(static_cast<int (ForgeAuxFixture::TProjectAccumulator<int, 7>::*)(int) const>(&ForgeAuxFixture::TProjectAccumulator<int, 7>::Add)),
        reinterpret_cast<void*>(&Replacement_168BB1C2275CBE71),
        &Invoke_168BB1C2275CBE71,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_168BB1C2275CBE71),
        true,
        TEXT("ForgeAuxFixture::TProjectAccumulator<int, 7>"),
        true,
        true,
        TEXT("sha256:54fa13f8f3e8f9c9c041e475fd149aad5a5a9fda5206ac5d37d4a570f2d9303e"),
        TEXT("ForgeAuxFixture_TProjectAccumulator_int_7_Add_168bb1c2"),
        true
    });
}

using FNativeFunction_2D0774436990047B = int32 (*)(const UFragment2DAsset*);

static FForgeInvokeResult Invoke_2D0774436990047B(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 0)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(0, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_2D0774436990047B>(FunctionAddress);

    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge instance method requires an instance"));
    }
    const auto MemberFunction = static_cast<int32 (UFragment2DAsset::*)() const>(&UFragment2DAsset::GetClampedWidth);
    if (FunctionAddress == ForgeMemberFunctionAddress(MemberFunction))
    {
        OutReturn = FForgeValue::FromInt32((static_cast<const UFragment2DAsset*>(Instance)->*MemberFunction)());
    }
    else
    {
        OutReturn = FForgeValue::FromInt32(NativeFunction(static_cast<const UFragment2DAsset*>(Instance)));
    }
    return FForgeInvokeResult::Success();
}

static int32 Replacement_2D0774436990047B(const UFragment2DAsset* Self)
{
    TArrayView<FForgeValue> Arguments;
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:2d0774436990047bed61680b20ac48b9e76a4748116e573bebd1ff1a22ee58d8"),
        const_cast<void*>(static_cast<const void*>(Self)),
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsInt32();
}

static void Register_2D0774436990047B(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:2d0774436990047bed61680b20ac48b9e76a4748116e573bebd1ff1a22ee58d8"),
        TEXT("UFragment2DAsset::GetClampedWidth"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        ForgeMemberFunctionAddress(static_cast<int32 (UFragment2DAsset::*)() const>(&UFragment2DAsset::GetClampedWidth)),
        reinterpret_cast<void*>(&Replacement_2D0774436990047B),
        &Invoke_2D0774436990047B,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") },
        TConstArrayView<FForgeTypeRef>(),
        true,
        TEXT("UFragment2DAsset"),
        true,
        true,
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        TEXT("UFragment2DAsset_GetClampedWidth_2d077443"),
        true
    });
}

static constexpr FForgeTypeRef ParameterTypes_4136A308C9F1BECF[] = { FForgeTypeRef{ EForgeValueType::Array, TEXT("TArray_int"), FForgeTypeRef::EPassingMode::ConstReference } };
using FNativeFunction_4136A308C9F1BECF = TArray<int32> (*)(const TArray<int32> &);

static FForgeInvokeResult Invoke_4136A308C9F1BECF(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_4136A308C9F1BECF>(FunctionAddress);

    OutReturn = ForgeValueFromNative_TARRAY_INT32(NativeFunction(ForgeNativeFromValue_TARRAY_INT32(Arguments[0])));
    return FForgeInvokeResult::Success();
}

static TArray<int32> Replacement_4136A308C9F1BECF(const TArray<int32> & Values)
{
    FForgeValue ArgumentStorage[] = { ForgeValueFromNative_TARRAY_INT32(Values) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:4136a308c9f1becf9f05e54b34c150aa221143bda06cc06adcbc00599cb8518d"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ForgeNativeFromValue_TARRAY_INT32(ReturnValue);
}

static void Register_4136A308C9F1BECF(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:4136a308c9f1becf9f05e54b34c150aa221143bda06cc06adcbc00599cb8518d"),
        TEXT("ForgeAuxFixture::AdvanceProjectValues"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<TArray<int32> (*)(const TArray<int32> &)>(&ForgeAuxFixture::AdvanceProjectValues)),
        reinterpret_cast<void*>(&Replacement_4136A308C9F1BECF),
        &Invoke_4136A308C9F1BECF,
        FForgeTypeRef{ EForgeValueType::Array, TEXT("TArray_int") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_4136A308C9F1BECF),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_A1F12EAE91660732[] = { FForgeTypeRef{ EForgeValueType::Float, TEXT("float") } };
using FNativeFunction_A1F12EAE91660732 = float (*)(float);

static FForgeInvokeResult Invoke_A1F12EAE91660732(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 1)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(1, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_A1F12EAE91660732>(FunctionAddress);

    OutReturn = FForgeValue::FromFloat(NativeFunction(Arguments[0].AsFloat()));
    return FForgeInvokeResult::Success();
}

static float Replacement_A1F12EAE91660732(float Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromFloat(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:a1f12eae91660732d06e50662480d2a6a4d4f472397a6842111cac5553f545d1"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_A1F12EAE91660732(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:a1f12eae91660732d06e50662480d2a6a4d4f472397a6842111cac5553f545d1"),
        TEXT("ForgeAuxFixture::CrossModuleValue"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<float (*)(float)>(&ForgeAuxFixture::CrossModuleValue)),
        reinterpret_cast<void*>(&Replacement_A1F12EAE91660732),
        &Invoke_A1F12EAE91660732,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_A1F12EAE91660732),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

static constexpr FForgeTypeRef ParameterTypes_A25E2C89331BCEEE[] = { FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") }, FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") } };
using FNativeFunction_A25E2C89331BCEEE = int32 (*)(int32, int32);

static FForgeInvokeResult Invoke_A25E2C89331BCEEE(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 2)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(2, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_A25E2C89331BCEEE>(FunctionAddress);

    OutReturn = FForgeValue::FromInt32(NativeFunction(Arguments[0].AsInt32(), Arguments[1].AsInt32()));
    return FForgeInvokeResult::Success();
}

static int32 Replacement_A25E2C89331BCEEE(int32 Base, int32 Value)
{
    FForgeValue ArgumentStorage[] = { FForgeValue::FromInt32(Base), FForgeValue::FromInt32(Value) };
    TArrayView<FForgeValue> Arguments(ArgumentStorage);
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:a25e2c89331bceee5c539b11bb38f077281ccd8deea1191305a0162fac5ad5aa"),
        nullptr,
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsInt32();
}

static void Register_A25E2C89331BCEEE(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:a25e2c89331bceee5c539b11bb38f077281ccd8deea1191305a0162fac5ad5aa"),
        TEXT("ForgeAuxFixture::ApplyProjectTemplate"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        reinterpret_cast<void*>(static_cast<int32 (*)(int32, int32)>(&ForgeAuxFixture::ApplyProjectTemplate)),
        reinterpret_cast<void*>(&Replacement_A25E2C89331BCEEE),
        &Invoke_A25E2C89331BCEEE,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") },
        TConstArrayView<FForgeTypeRef>(ParameterTypes_A25E2C89331BCEEE),
        false,
        TEXT(""),
        true,
        true,
        TEXT(""),
        TEXT(""),
        false
    });
}

using FNativeFunction_EE7D2ECAB0D592CE = float (*)(const UFragment2DAsset*);

static FForgeInvokeResult Invoke_EE7D2ECAB0D592CE(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 0)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(0, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_EE7D2ECAB0D592CE>(FunctionAddress);

    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge instance method requires an instance"));
    }
    const auto MemberFunction = static_cast<float (UFragment2DAsset::*)() const>(&UFragment2DAsset::GetClampedCellSize);
    if (FunctionAddress == ForgeMemberFunctionAddress(MemberFunction))
    {
        OutReturn = FForgeValue::FromFloat((static_cast<const UFragment2DAsset*>(Instance)->*MemberFunction)());
    }
    else
    {
        OutReturn = FForgeValue::FromFloat(NativeFunction(static_cast<const UFragment2DAsset*>(Instance)));
    }
    return FForgeInvokeResult::Success();
}

static float Replacement_EE7D2ECAB0D592CE(const UFragment2DAsset* Self)
{
    TArrayView<FForgeValue> Arguments;
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:ee7d2ecab0d592ce0680696b9aa51b79bff69a66a95e32912f7747f1c0a91a74"),
        const_cast<void*>(static_cast<const void*>(Self)),
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsFloat();
}

static void Register_EE7D2ECAB0D592CE(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:ee7d2ecab0d592ce0680696b9aa51b79bff69a66a95e32912f7747f1c0a91a74"),
        TEXT("UFragment2DAsset::GetClampedCellSize"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        ForgeMemberFunctionAddress(static_cast<float (UFragment2DAsset::*)() const>(&UFragment2DAsset::GetClampedCellSize)),
        reinterpret_cast<void*>(&Replacement_EE7D2ECAB0D592CE),
        &Invoke_EE7D2ECAB0D592CE,
        FForgeTypeRef{ EForgeValueType::Float, TEXT("float") },
        TConstArrayView<FForgeTypeRef>(),
        true,
        TEXT("UFragment2DAsset"),
        true,
        true,
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        TEXT("UFragment2DAsset_GetClampedCellSize_ee7d2eca"),
        true
    });
}

using FNativeFunction_FECE7216CB6C84BC = int32 (*)(const UFragment2DAsset*);

static FForgeInvokeResult Invoke_FECE7216CB6C84BC(
    void* FunctionAddress,
    void* Instance,
    TArrayView<FForgeValue> Arguments,
    FForgeValue& OutReturn)
{
    if (Arguments.Num() != 0)
    {
        return FForgeInvokeResult::ArgumentCountMismatch(0, Arguments.Num());
    }

    const auto NativeFunction = reinterpret_cast<FNativeFunction_FECE7216CB6C84BC>(FunctionAddress);

    if (Instance == nullptr)
    {
        return FForgeInvokeResult::Failure(TEXT("Forge instance method requires an instance"));
    }
    const auto MemberFunction = static_cast<int32 (UFragment2DAsset::*)() const>(&UFragment2DAsset::GetClampedHeight);
    if (FunctionAddress == ForgeMemberFunctionAddress(MemberFunction))
    {
        OutReturn = FForgeValue::FromInt32((static_cast<const UFragment2DAsset*>(Instance)->*MemberFunction)());
    }
    else
    {
        OutReturn = FForgeValue::FromInt32(NativeFunction(static_cast<const UFragment2DAsset*>(Instance)));
    }
    return FForgeInvokeResult::Success();
}

static int32 Replacement_FECE7216CB6C84BC(const UFragment2DAsset* Self)
{
    TArrayView<FForgeValue> Arguments;
    FForgeValue ReturnValue;
    const FForgeInvokeResult Result = InvokeForgePatchedFunction(
        TEXT("sha256:fece7216cb6c84bca568ecaec4aee6acceb3423c15b459a59bc1e4a4539f65b3"),
        const_cast<void*>(static_cast<const void*>(Self)),
        Arguments,
        ReturnValue);
    checkf(Result.bSuccess, TEXT("Forge Patch invocation failed: %s"), *Result.Error);

    return ReturnValue.AsInt32();
}

static void Register_FECE7216CB6C84BC(IForgeBindingRegistry& Registry)
{
    Registry.RegisterFunction(FForgeFunctionBinding{
        TEXT("sha256:fece7216cb6c84bca568ecaec4aee6acceb3423c15b459a59bc1e4a4539f65b3"),
        TEXT("UFragment2DAsset::GetClampedHeight"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT,
        ForgeMemberFunctionAddress(static_cast<int32 (UFragment2DAsset::*)() const>(&UFragment2DAsset::GetClampedHeight)),
        reinterpret_cast<void*>(&Replacement_FECE7216CB6C84BC),
        &Invoke_FECE7216CB6C84BC,
        FForgeTypeRef{ EForgeValueType::Int32, TEXT("int32") },
        TConstArrayView<FForgeTypeRef>(),
        true,
        TEXT("UFragment2DAsset"),
        true,
        true,
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        TEXT("UFragment2DAsset_GetClampedHeight_fece7216"),
        true
    });
}

static void RegisterAllBindings(IForgeBindingRegistry& Registry)
{
    Registry.RegisterReflectionMapping(FForgeReflectionMappingBinding{
        TEXT("sha256:521639e3502ed390563b0bf27d4c3efe3f19b863425c2b83b0e5ba0c7e732864"),
        EForgeReflectionKind::Class,
        TEXT("UFragment2DAsset"),
        TEXT("/Script/MatterFlux.Fragment2DAsset"),
        TEXT("sha256:38175349e16a3013e5f0158dcbcb9f14608cb70507d6fbb87d90cd6443f4e99b"),
        TEXT(""),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT
    });
    Registry.RegisterReflectionMapping(FForgeReflectionMappingBinding{
        TEXT("sha256:650405a527ae996974fbd9f7cb59b1bc8648d309bc9f7dbc02afb3beb2b46981"),
        EForgeReflectionKind::Property,
        TEXT("UFragment2DAsset::MaxFragmentsPerBreak"),
        TEXT("/Script/MatterFlux.Fragment2DAsset:MaxFragmentsPerBreak"),
        TEXT("sha256:a2d26d8dad93c52aa28c0e4d0f9dd35c6c7df4e938a2a2939b19aaf035b59ae7"),
        TEXT("sha256:b060a83351782abcff23cfd642c3d4df15113a6bfdc48243927e5b47185ba48a"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT
    });
    Registry.RegisterReflectionMapping(FForgeReflectionMappingBinding{
        TEXT("sha256:adaf5e9ffd34ef091c0fe14c4806b189265664d8b5d40bbd14bacb0302d74fa8"),
        EForgeReflectionKind::Property,
        TEXT("UFragment2DAsset::MinFragmentAreaPixels"),
        TEXT("/Script/MatterFlux.Fragment2DAsset:MinFragmentAreaPixels"),
        TEXT("sha256:97bc0770fe58c3917afdd111adeec0304c9ff026236b6b1fc08a3e5beb85023e"),
        TEXT("sha256:5ba73d88f84437d846982a251ea837f3c0372719bae78154676811ffd26f351c"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT
    });
    Registry.RegisterReflectionMapping(FForgeReflectionMappingBinding{
        TEXT("sha256:ae52d6f799e40fcf33f610836587d71b341f97c429f2cd1e56507d9e7f059797"),
        EForgeReflectionKind::Property,
        TEXT("UFragment2DAsset::MaskWidth"),
        TEXT("/Script/MatterFlux.Fragment2DAsset:MaskWidth"),
        TEXT("sha256:3cf7594d1b3cfa8ede4b5351e5472a1363211798722fbea06e6cfa5c81170047"),
        TEXT("sha256:9ab97f2cda891e456db67954c4dfca4603e270717d493d0d0c10c3e953da8328"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT
    });
    Registry.RegisterReflectionMapping(FForgeReflectionMappingBinding{
        TEXT("sha256:c55f5e7d7c771717f13c2d1366d550f43170a42cb6bbb0adf5222e4221dc2cd5"),
        EForgeReflectionKind::Property,
        TEXT("UFragment2DAsset::MaskHeight"),
        TEXT("/Script/MatterFlux.Fragment2DAsset:MaskHeight"),
        TEXT("sha256:3645de237d7f0b99b1827ffc8ff6a8b135c647d5176f5f0d17558e8bf552f7ab"),
        TEXT("sha256:e5ab6b08eee4c465173482a07331d31fcd26061c86cd3d75ae3e0952d63136a8"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT
    });
    Registry.RegisterReflectionMapping(FForgeReflectionMappingBinding{
        TEXT("sha256:c9b5623f2bb8220054a2fe6645374376df612ea835938abc11e2bfcb4db5b8e3"),
        EForgeReflectionKind::Property,
        TEXT("UFragment2DAsset::CellSize"),
        TEXT("/Script/MatterFlux.Fragment2DAsset:CellSize"),
        TEXT("sha256:42f1df32180833a3ae8fbfd24676b5ba6f4ff93c96a7f4d1916e83072300a175"),
        TEXT("sha256:e8e5dad8b3eea0fd93288a9eb7d6a7c5248a8f7d7146bdffb890ffd2fa81709c"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT
    });
    Registry.RegisterReflectionMapping(FForgeReflectionMappingBinding{
        TEXT("sha256:f992d69e90595be1db3f3b8d895980dde5c97f3e7db2dfab7d984d05d9f0ff1e"),
        EForgeReflectionKind::Property,
        TEXT("UFragment2DAsset::SolidMask"),
        TEXT("/Script/MatterFlux.Fragment2DAsset:SolidMask"),
        TEXT("sha256:b61092acfb6c36e01ddd3aa8c5b85b576101520c245ba123ce616f1be789042e"),
        TEXT("sha256:f947af5da902493c7bcf808f5c599951ce3a2e80341d281c9879f34ce62394dc"),
        FName(TEXT("MatterFlux")),
        MATTERFLUX_FORGE_BUILD_FINGERPRINT
    });
    RegisterType_FORGEAUXFIXTURE_TPROJECTACCUMULATOR_INT_7(Registry);
    RegisterType_TARRAY_INT32(Registry);
    RegisterType_UFRAGMENT2DASSET(Registry);
    RegisterField_5BA73D88F84437D8(Registry);
    RegisterField_9AB97F2CDA891E45(Registry);
    RegisterField_B060A83351782ABC(Registry);
    RegisterField_D12954423ABE9235(Registry);
    RegisterField_E5AB6B08EEE4C465(Registry);
    RegisterField_E8E5DAD8B3EEA0FD(Registry);

    Register_168BB1C2275CBE71(Registry);
    Register_2D0774436990047B(Registry);
    Register_4136A308C9F1BECF(Registry);
    Register_A1F12EAE91660732(Registry);
    Register_A25E2C89331BCEEE(Registry);
    Register_EE7D2ECAB0D592CE(Registry);
    Register_FECE7216CB6C84BC(Registry);
}

static FForgeAutoModuleRegistrar GForgeRegistrar(FForgeModuleBindings{
    FName(TEXT("MatterFlux")),
    MATTERFLUX_FORGE_BUILD_FINGERPRINT,
    &RegisterAllBindings
});
} // namespace
